### PR TITLE
[WIP] Upstream soem integration

### LINKED ISSUE #16: Update to latest upstream SOEM release
The latest [release of upstream SOEM](https://github.com/OpenEtherCATsociety/SOEM/releases) is ~1.3.1, there is a release candidate for 1.3.3 available as well. (1.3.2 is marked as `DON'T use`)~ 1.4, as stated by @FelixBlix in https://github.com/mgruhler/soem/issues/16#issuecomment-507632325.
If possible, it would be nice to update to the latest release.

Updating to 1.3.1 has initally been proposed in #9.

However, there are apparently some issues with 1.3.1, as discussed in https://github.com/mgruhler/soem/issues/5#issuecomment-312478442 

> As mentioned in issue #9 , I tried using 1.3.1 myself. It did compile, but wasn't working at all. I think the main issue is the Added multi-threaded configuration for parallel configurations of slaves

This would need to be thoroughly tested though.

### LINKED ISSUE #17: Improve header handling
SOEM expects headers in a flat directory hierarchy (i.e. `<headerpath>`). In contrast, ROS, by convention, expects headers in a subdirectory which is named after the ROS package (i.e. `<pkg>/<headerpath>`).

Currently, with the intention of not having to adapt any soem headers, but still somehow stick to the ROS convention, the `soem` headers are installed to `soem/*.h`.

This leads to the problem, that any ROS code building against `soem` runs into problems with finding headers.
A work around to overcome this is shown in the [Usage section of the README.md](https://github.com/mgruhler/soem#Usage).

This should be cleaned up such that we don't break existing code but without having to adapt any soem sources.

This has been reported multiple time, e.g. in #4 and #8

### LINKED ISSUE #22: Issue when exporting a new package with SOEM
Hi, 

I am trying to set up a new package (`pkg_a`) that depends on SOEM. I got that working properly. The problem appears when I use this new package with another package (`pkg_b`), I have to add `${soem_INCLUDE_DIRS}/soem` in the `include_directories` of `pkg_b` again. 

I am looking to find a solution that this is taken care of in `pkg_a`. Since I cannot add `${soem_INCLUDE_DIRS}/soem` in `catkin_package INCLUDE_DIRS` of `pkg_a` (I would get a non-package include path error from `catkin_lint`), I am curious if there is a way to do this. 

Thanks!

### PR DESCRIPTION
**Pull request by mgruhler**
Fixes #16 by including SOEM Release 1.4.0 as git submodule (originally suggested in #11) and basically starting from scratch...
Fixes #17 and fixes #22 by providing proper CFG_ETRAS file

I tested this from both, devel and install space, using `catkin_make` and `catkin_tools` with the hardware available to me. I don't see any degradation or other performance issues.

Downside to this approach: This is a "breaking change" in how the current system is used in dependent packages as the way to fix the header issue previously has been to add `${soem_INCLUDE_DIRS}/soem` to the `include_directories` statement. This does not work anymore due to the exported include paths.

Before merging this, some more tests should be performed by other users of this package!

Also, once this has been merged, a decision has to be made about how to best proceed with a release that is NOT backwards compatible!

### CODE REVIEW

**Comment by mgruhler** [comment]
Feedback from @FelixBlix, @wongkaiweng, @jonbinney would be highly appreciated.

Obviously any feedback on this approach (if this package is still used by you guys) from @smits @meyerj @shaun-edwards will also be very valuable!

**Comment by jonbinney** [comment]
Wow, @mgruhler this is great! I tested three different setups, and all compiled successfully using your branch:
- `cakin_make` a package that depends on soem in the same catkin workspace as soem
- `catkin_make` soem in its own catkin workspace, source `devel` setup file, then compile a package that depends on soem in a child catkin_workspace
- `caktin_make` soem in its own catkin workspace, source `install` setup file, then compile a package that depends on soem in a child catkin workspace

I did have a little trouble because i'm not used to submodules. After switching to the `upstream_soem_integration` branch, i forgot to run `git submodule init`. I'm not sure how `.rosinstall` based tools like `rosws` and `wstool` would handle this.

What do you think about using subtree instead of submodule? It should be similarly easy to update soem here when new versions come out, but it would make it easier for users of this package because they would get updated code with a simple `git clone`.

**Comment by mgruhler** [comment]
@jonbinney thx for the feedback. Great that this seems to work for you too :+1:

I must admit that the `git submodule` approach is not very common (and many people discourage using submodules at all). I figured it shouldn't be a big issue since I don't think many people will use this package from source often.  As basically there should be a new release here whenever there is a new upstream release, but I don't see a reason for other changes (hopefully...)

That being said:
I also don't think that patching upstream soem in the submodule will be something that happens often, if at all. This would be the main justification for having a submodule, as this would provide a very easy way to bring those changes back to upstream.
Thus, the subtree approach (new to me!) would be definitely worth a try. It might be more complex to integrate and a lot more complicated to split out upstream changes. But the benefits of not requiring people to jump through the submodule hoops for getting a compilable version could outweigh that.
However, it might be a week or so until I find the time to test this...

An alternative would be provide a big fat Cmake error if the submodule is not checked out.

But you are also right that I don't know how many of the ROS Tools ( `wstool`, on the one hand, but also `bloom`) handle submodules.

**Comment by mgruhler** [comment]
@jonbinney I found a little spare time on my hands and the subtree approach intrigued me. So I played a little bit around with it and it seems to work. see #24. Would be great if you could test this again.

**Comment by wongkaiweng** [comment]
@mgruhler I tried this PR and also #24. Both of them worked for me with `${soem_INCLUDE_DIRS}/soem` removed from my packages. I definitely prefer #24 as it does not require a submodule initialization. Thank you for the fix!

**Comment by mgruhler** [comment]
closing in favor of #24 as it seems to be consensus that using git subtree is the preferred approach over git submodules.

**Pull request closed without merging**
