### PR TITLE
Updated to the latest version of SOEM(1.3.2)

### PR DESCRIPTION
**Pull request by qboticslabs**
This will replace version 1.3 to 1.3.2.

The latest code is retrieved from the following link
`https://github.com/OpenEtherCATsociety/SOEM`

### CODE REVIEW

**Comment by mgruhler** [comment]
@qboticslabs thanks. Why did you close this directly?

**Comment by qboticslabs** [comment]
Updated to the latest version of SOEM(1.3.2)

**Comment by mgruhler** [comment]
thanks for reopening @qboticslabs 

Again, why did you close this? Is this working? How did you test it?
See also #16 for possible errors. Then, is this the release 1.3.2-beta or the latest head?

**Comment by qboticslabs** [comment]
> thanks for reopening @qboticslabs
> 
> Again, why did you close this? Is this working? How did you test it?
> See also #16 for possible errors. Then, is this the release 1.3.2-beta or the latest head?

The latest version is building properly and examples are also working. However, I found some header file missing when I used 'soem' package as a dependency to another package. That need to be fixed. I will fix it and give the pull request later.

**Comment by mgruhler** [comment]
@qboticslabs thanks. What is the status on this? Did you figure out the `header file` issue? Is this the same as described in #17?

Also, please answer the follwing questions: 
- How did you test it? See also #16 for possible errors. 
- Is this the release 1.3.2-beta or the latest head? Please provide the respective commit SHA

**Comment by qboticslabs** [comment]
@mgruhler The package is building properly, but the issue is #17 . I can't able to fix it.

1)I have only tested the tools getting along with soem package such as slaveinfo, simple_test etc. That is working. I have tested it using an EtherCAT Slave

2)This is 1.3.2, not the beta version. I

**Comment by mgruhler** [comment]
@qboticslabs given that 1.3.2 is marked as 

> DON'T use

on the [release page](https://github.com/OpenEtherCATsociety/SOEM/releases) of the upstream repo, I'm a bit reluctant to merge this as is. Why not upgrading to 1.3.3-beta? This has been released on the same day...

Given that #16 is also not fully fixed by this, I'll close this now. Please feel free to reopen, if you want to update to the latest (pre)release.

**Pull request closed without merging**
